name: Release Pipeline
on:
  push:
    #branches:
    #  - 'release/v[0-9]+.[0-9]+'

env:
  RAILWAY_URL: truthful-morning-production.up.railway.app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      
      - name: Build
        run: go build -o dov-bear .


      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Hello, world!*"
                  }
                }
              ]
            }
