name: Release Pipeline
on:
  push:
    #branches:
    #  - 'release/v[0-9]+.[0-9]+'
    #if: "!startsWith(github.event.head_commit.message, '#NORUN')"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      
      - name: Build
        run: go build -o dov-bear .

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Application Provisioned",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* Charmaine Tan"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* e1112932@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation Number:* E1112932"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* \n ${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment URL:* \n ${{ secrets.RAILWAY_URL }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go",
                        "emoji": true
                      },
                      "url": "${{ secrets.RAILWAY_URL }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK