name: Release Pipeline
on:
  push:
    #branches:
    #  - 'release/v[0-9]+.[0-9]+'
env:
  RAILWAY_URL: truthful-morning-production.up.railway.app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      
      - name: Build
        run: go build -o dov-bear .

      - name: Debug Secret
        run: echo ${{ secrets.RAILWAY_URL }}


      - name: Notify Slack Fail
        if: failure()
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "general"
          slack-message: |
            GitHub build result: ${{ job.status }}
            ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
            <@${{ secrets.SLACK_WEBHOOK}}>
        env: